$owner = "Azure-Samples"
$repo = "visionary-lab"
$branch = "main"
$filePath = ".github/workflows/deploy.yml"
$fileContentUrl = "https://github.com/Azure-Samples/agents-escalation/blob/main/.github/workflows/azure-dev.yml"

# Download the file content from the URL
$response = Invoke-WebRequest -Uri $fileContentUrl -UseBasicParsing
$content = $response.Content

# Convert the content to Base64
$bytes = [System.Text.Encoding]::UTF8.GetBytes($content)
$encodedContent = [Convert]::ToBase64String($bytes)

# Define the commit message
$message = "Add new file via GH CLI"

# Use the GitHub CLI (gh) to create the file in the repository
gh api repos/$owner/$repo/contents/$filePath `
  --method PUT `
  -F message="$message" `
  -F content="$encodedContent" `
  -F branch="$branch"

Write-Output "File added successfully!"
