name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4  
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: aigbbemea.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/frontend.dockerfile
        push: true
        tags: aigbbemea.azurecr.io/visionarylab-frontend:${{ github.run_number }}


        